# This is a basic workflow that is manually triggered





name: CRABServer deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'CRABServer tag to deploy:'
        required: true
      hostName:
        description: 'Host where given tag should be deployed:'
        required: true   
        default: preprod
    steps:
      - id: get_environment
        run: |
          if [ "${{ github.event.inputs.hostName }}" = "test2" ]
          then
            echo "::set-output name=hostName::cmsweb-test2.cern.ch"
          elif [ "${{ github.event.inputs.hostName }}" = "preprod" ]
          then
            echo "::set-output name=hostName::cmsweb-testbed.cern.ch"
          fi        

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke crabserver deployment
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '{ "hostName": "${{ github.event.inputs.hostName }}", "tag" : "${{ github.event.inputs.tag }}" }'    
      #uses: joelwmale/webhook-action@master
      #with:
      #  url: ${{ secrets.WEBHOOK_URL }}
      #  headers: '{"repository": "ddaina/crabserver"}'
      #  body: '{"event": "deployment", "repository": "ddaina/crabserver"}'  
        
    
    

        
        
