# This is a basic workflow that is manually triggered

name: Manual workflow v1

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'CRABServer tag to deploy:'
        required: true
      environment:
        description: 'Host where given tag should be deployed:'
        required: true   
        default: preprod

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Invoke crabserver deployment
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        headers: '{"repository": "ddaina/crabserver"}'
        body: '{"event": "deployment", "repository": "ddaina/crabserver"}'  
        
    #  uses: distributhor/workflow-webhook@v1
    #  env:
    #    webhook_url: ${{ secrets.WEBHOOK_URL }}
    #    webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
    #    data: '{ "weapon": "hammer", "drink" : "beer" }'    
    

        
        
